services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb

  clickhouse:
    image:  clickhouse/clickhouse-server:latest
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - 9000:9000
      - 8123:8123

  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379

  nats:
    image: nats:latest
    hostname: nats
    container_name: nats
    ports:
      - 4222:4222

  my-svc:
    build: .
    container_name: my-svc
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - clickhouse
      - redis
      - nats
    environment:
      POSTGRES_URL: "postgres://postgres:mysecretpassword@postgres:5432/mydb"
      REDIS_URL: "redis://redis:6379"
      NATS_URL: "nats://nats:4222"
      CLICKHOUSE_URL: "clickhouse://clickhouse:8123"


